import { StarterPalette } from '../types';

export const starterPalettes: StarterPalette[] = [
    {
        paletteName: 'Material UI Colors',
        id: 'material-ui-colors',
        emoji: '🎨',
        colors: [
            { name: 'red', hex: '#F44336' },
            { name: 'pink', hex: '#E91E63' },
            { name: 'purple', hex: '#9C27B0' },
            { name: 'deeppurple', hex: '#673AB7' },
            { name: 'indigo', hex: '#3F51B5' },
            { name: 'blue', hex: '#2196F3' },
            { name: 'lightblue', hex: '#03A9F4' },
            { name: 'cyan', hex: '#00BCD4' },
            { name: 'teal', hex: '#009688' },
            { name: 'green', hex: '#4CAF50' },
            { name: 'lightgreen', hex: '#8BC34A' },
            { name: 'lime', hex: '#CDDC39' },
            { name: 'yellow', hex: '#FFEB3B' },
            { name: 'amber', hex: '#FFC107' },
            { name: 'orange', hex: '#FF9800' },
            { name: 'deeporange', hex: '#FF5722' },
            { name: 'brown', hex: '#795548' },
            { name: 'grey', hex: '#9E9E9E' },
            { name: 'bluegrey', hex: '#607D8B' }
        ]
    },
    {
        paletteName: 'Flat UI Colors v1',
        id: 'flat-ui-colors-v1',
        emoji: '🤙',
        colors: [
            { name: 'Turquoise', hex: '#1abc9c' },
            { name: 'Emerald', hex: '#2ecc71' },
            { name: 'PeterRiver', hex: '#3498db' },
            { name: 'Amethyst', hex: '#9b59b6' },
            { name: 'WetAsphalt', hex: '#34495e' },
            { name: 'GreenSea', hex: '#16a085' },
            { name: 'Nephritis', hex: '#27ae60' },
            { name: 'BelizeHole', hex: '#2980b9' },
            { name: 'Wisteria', hex: '#8e44ad' },
            { name: 'MidnightBlue', hex: '#2c3e50' },
            { name: 'SunFlower', hex: '#f1c40f' },
            { name: 'Carrot', hex: '#e67e22' },
            { name: 'Alizarin', hex: '#e74c3c' },
            { name: 'Clouds', hex: '#ecf0f1' },
            { name: 'Concrete', hex: '#95a5a6' },
            { name: 'Orange', hex: '#f39c12' },
            { name: 'Pumpkin', hex: '#d35400' },
            { name: 'Pomegranate', hex: '#c0392b' },
            { name: 'Silver', hex: '#bdc3c7' },
            { name: 'Asbestos', hex: '#7f8c8d' }
        ]
    },
    {
        paletteName: 'Flat UI Colors Dutch',
        id: 'flat-ui-colors-dutch',
        emoji: '🇳🇱',
        colors: [
            { name: 'Sunflower', hex: '#FFC312' },
            { name: 'Energos', hex: '#C4E538' },
            { name: 'BlueMartina', hex: '#12CBC4' },
            { name: 'LavenderRose', hex: '#FDA7DF' },
            { name: 'BaraRose', hex: '#ED4C67' },
            { name: 'RadiantYellow', hex: '#F79F1F' },
            { name: 'AndroidGreen', hex: '#A3CB38' },
            { name: 'MediterraneanSea', hex: '#1289A7' },
            { name: 'LavenderTea', hex: '#D980FA' },
            { name: 'VerryBerry', hex: '#B53471' },
            { name: 'PuffinsBill', hex: '#EE5A24' },
            { name: 'PixelatedGrass', hex: '#009432' },
            { name: 'MerchantMarineBlue', hex: '#0652DD' },
            { name: 'ForgottenPurple', hex: '#9980FA' },
            { name: 'HollyHock', hex: '#833471' },
            { name: 'RedPigment', hex: '#EA2027' },
            { name: 'TurkishAqua', hex: '#006266' },
            { name: '20000LeaguesUnderTheSea', hex: '#1B1464' },
            { name: 'CircumorbitalRing', hex: '#5758BB' },
            { name: 'MagentaPurple', hex: '#6F1E51' }
        ]
    },
    {
        paletteName: 'Flat UI Colors American',
        id: 'flat-ui-colors-american',
        emoji: '🇺🇸',
        colors: [
            { name: 'LightGreenishBlue', hex: '#55efc4' },
            { name: 'FadedPoster', hex: '#81ecec' },
            { name: 'GreenDarnerTail', hex: '#74b9ff' },
            { name: 'ShyMoment', hex: '#a29bfe' },
            { name: 'CityLights', hex: '#dfe6e9' },
            { name: 'MintLeaf', hex: '#00b894' },
            { name: 'RobinsEggBlue', hex: '#00cec9' },
            { name: 'ElectronBlue', hex: '#0984e3' },
            { name: 'ExodusFruit', hex: '#6c5ce7' },
            { name: 'SoothingBreeze', hex: '#b2bec3' },
            { name: 'SourLemon', hex: '#ffeaa7' },
            { name: 'FirstDate', hex: '#fab1a0' },
            { name: 'PinkGlamour', hex: '#ff7675' },
            { name: 'Pico8Pink', hex: '#fd79a8' },
            { name: 'AmericanRiver', hex: '#636e72' },
            { name: 'BrightYarrow', hex: '#fdcb6e' },
            { name: 'OrangeVille', hex: '#e17055' },
            { name: 'Chi-Gong', hex: '#d63031' },
            { name: 'PrunusAvium', hex: '#e84393' },
            { name: 'DraculaOrchid', hex: '#2d3436' }
        ]
    },
    {
        paletteName: 'Flat UI Colors Aussie',
        id: 'flat-ui-colors-aussie',
        emoji: '🇦🇺',
        colors: [
            { name: 'Beekeeper', hex: '#f6e58d' },
            { name: 'SpicedNectarine', hex: '#ffbe76' },
            { name: 'PinkGlamour', hex: '#ff7979' },
            { name: 'JuneBud', hex: '#badc58' },
            { name: 'CoastalBreeze', hex: '#dff9fb' },
            { name: 'Turbo', hex: '#f9ca24' },
            { name: 'QuinceJelly', hex: '#f0932b' },
            { name: 'CarminePink', hex: '#eb4d4b' },
            { name: 'PureApple', hex: '#6ab04c' },
            { name: 'HintOfIcePack', hex: '#c7ecee' },
            { name: 'MiddleBlue', hex: '#7ed6df' },
            { name: 'Heliotrope', hex: '#e056fd' },
            { name: 'ExodusFruit', hex: '#686de0' },
            { name: 'DeepKoamaru', hex: '#30336b' },
            { name: 'SoaringEagle', hex: '#95afc0' },
            { name: 'GreenlandGreen', hex: '#22a6b3' },
            { name: 'SteelPink', hex: '#be2edd' },
            { name: 'Blurple', hex: '#4834d4' },
            { name: 'DeepCove', hex: '#130f40' },
            { name: 'WizardGrey', hex: '#535c68' }
        ]
    },
    {
        paletteName: 'Flat UI Colors British',
        id: 'flat-ui-colors-british',
        emoji: '🇬🇧',
        colors: [
            { name: 'ProtossPylon', hex: '#00a8ff' },
            { name: 'Periwinkle', hex: '#9c88ff' },
            { name: 'Rise-N-Shine', hex: '#fbc531' },
            { name: 'DownloadProgress', hex: '#4cd137' },
            { name: 'Seabrook', hex: '#487eb0' },
            { name: 'VanaDylBlue', hex: '#0097e6' },
            { name: 'MattPurple', hex: '#8c7ae6' },
            { name: 'NanohanachaGold', hex: '#e1b12c' },
            { name: 'SkirretGreen', hex: '#44bd32' },
            { name: 'Naval', hex: '#40739e' },
            { name: 'NasturcianFlower', hex: '#e84118' },
            { name: 'LynxWhite', hex: '#f5f6fa' },
            { name: 'BlueberrySoda', hex: '#7f8fa6' },
            { name: 'MazarineBlue', hex: '#273c75' },
            { name: 'BlueNights', hex: '#353b48' },
            { name: 'HarleyOrange', hex: '#c23616' },
            { name: 'HintOfPensive', hex: '#dcdde1' },
            { name: 'ChainGangGrey', hex: '#718093' },
            { name: 'PicoVoid', hex: '#192a56' },
            { name: 'ElectroMagnetic', hex: '#2f3640' }
        ]
    },
    {
        paletteName: 'Flat UI Colors Spanish',
        id: 'flat-ui-colors-spanish',
        emoji: '🇪🇸',
        colors: [
            { name: 'JacksonsPurple', hex: '#40407a' },
            { name: 'C64Purple', hex: '#706fd3' },
            { name: 'SwanWhite', hex: '#f7f1e3' },
            { name: 'SummerSky', hex: '#34ace0' },
            { name: 'CelestialGreen', hex: '#33d9b2' },
            { name: 'LuckyPoint', hex: '#2c2c54' },
            { name: 'Liberty', hex: '#474787' },
            { name: 'HotStone', hex: '#aaa69d' },
            { name: 'DevilBlue', hex: '#227093' },
            { name: 'PalmSpringsSplash', hex: '#218c74' },
            { name: 'FlourescentRed', hex: '#ff5252' },
            { name: 'SyntheticPumpkin', hex: '#ff793f' },
            { name: 'CrocodileTooth', hex: '#d1ccc0' },
            { name: 'MandarinSorbet', hex: '#ffb142' },
            { name: 'SpicedButterNut', hex: '#ffda79' },
            { name: 'EyeOfNewt', hex: '#b33939' },
            { name: 'ChileanFire', hex: '#cd6133' },
            { name: 'GreyPorcelain', hex: '#84817a' },
            { name: 'AlamedaOchre', hex: '#cc8e35' },
            { name: 'Desert', hex: '#ccae62' }
        ]
    },
    {
        paletteName: 'Flat UI Colors Indian',
        id: 'flat-ui-colors-indian',
        emoji: '🇮🇳',
        colors: [
            { name: 'OrchidOrange', hex: '#FEA47F' },
            { name: 'SpiroDiscoBall', hex: '#25CCF7' },
            { name: 'HoneyGlow', hex: '#EAB543' },
            { name: 'SweetGarden', hex: '#55E6C1' },
            { name: 'FallingStar', hex: '#CAD3C8' },
            { name: 'RichGardenia', hex: '#F97F51' },
            { name: 'ClearChill', hex: '#1B9CFC' },
            { name: 'WhitePepper', hex: '#F8EFBA' },
            { name: 'Keppel', hex: '#58B19F' },
            { name: 'ShipsOfficer', hex: '#2C3A47' },
            { name: 'FieryFuchsia', hex: '#B33771' },
            { name: 'BlueBell', hex: '#3B3B98' },
            { name: 'GeorgiaPeach', hex: '#FD7272' },
            { name: 'OasisStream', hex: '#9AECDB' },
            { name: 'BrightUbe', hex: '#D6A2E8' },
            { name: 'MagentaPurple', hex: '#6D214F' },
            { name: 'EndingNavyBlue', hex: '#182C61' },
            { name: 'SasquatchSocks', hex: '#FC427B' },
            { name: 'PineGlade', hex: '#BDC581' },
            { name: 'HighlighterLavender', hex: '#82589F' }
        ]
    },
    {
        paletteName: 'Flat UI Colors French',
        id: 'flat-ui-colors-french',
        emoji: '🇫🇷',
        colors: [
            { name: 'FlatFlesh', hex: '#fad390' },
            { name: 'MelonMelody', hex: '#f8c291' },
            { name: 'Livid', hex: '#6a89cc' },
            { name: 'Spray', hex: '#82ccdd' },
            { name: 'ParadiseGreen', hex: '#b8e994' },
            { name: 'SquashBlossom', hex: '#f6b93b' },
            { name: 'MandarinRed', hex: '#e55039' },
            { name: 'AzraqBlue', hex: '#4a69bd' },
            { name: 'Dupain', hex: '#60a3bc' },
            { name: 'AuroraGreen', hex: '#78e08f' },
            { name: 'IcelandPoppy', hex: '#fa983a' },
            { name: 'TomatoRed', hex: '#eb2f06' },
            { name: 'YueGuangBlue', hex: '#1e3799' },
            { name: 'GoodSamaritan', hex: '#3c6382' },
            { name: 'Waterfall', hex: '#38ada9' },
            { name: 'CarrotOrange', hex: '#e58e26' },
            { name: 'JalapenoRed', hex: '#b71540' },
            { name: 'DarkSapphire', hex: '#0c2461' },
            { name: 'ForestBlues', hex: '#0a3d62' },
            { name: 'ReefEncounter', hex: '#079992' }
        ]
    }
];
